{
  "format_version": 2,
  "sksl": {
    "entrypoint": "post_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uRes;\nuniform float uTime;\nuniform float uVignette;\nuniform float uGrain;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_hash(vec2 p)\n{\n    vec3 p3 = fract(p.xyx * 0.103100001811981201171875);\n    p3 += vec3(dot(p3, p3.yzx + vec3(33.3300018310546875)));\n    return fract((p3.x + p3.y) * p3.z);\n}\n\nvoid FLT_main()\n{\n    vec2 frag = FLT_flutter_local_FlutterFragCoord();\n    vec2 q = (frag / uRes) - vec2(0.5);\n    q.x *= (uRes.x / uRes.y);\n    float vig = smoothstep(0.25, 0.949999988079071044921875, length(q) * (1.0 + (uVignette * 0.800000011920928955078125))) * (0.550000011920928955078125 + (0.449999988079071044921875 * uVignette));\n    vec2 param = floor(frag * 0.75) + vec2(fract(uTime * 13.0) * 311.0);\n    float g = FLT_flutter_local_hash(param) - 0.5;\n    float ga = abs(g) * uGrain;\n    float gc = float(g > 0.0);\n    float a = ga + (vig * (1.0 - ga));\n    fragColor = vec4(vec3(gc * ga), a);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uRes",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uVignette",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uGrain",
        "rows": 1,
        "type": 10
      }
    ]
  }
}